-- =============================================
-- FoldNest E-Commerce — Admin Seed Data
-- Default Admin Credentials:
--   Username: admin
--   Email:    admin@foldnest.com
--   Password: Admin@123
-- IMPORTANT: Change these credentials after first login!
-- =============================================

USE ecommerce_db;

-- The password hash below is bcrypt hash of 'Admin@123'
-- Generated using PHP: password_hash('Admin@123', PASSWORD_BCRYPT)
INSERT INTO admins (username, email, password_hash, full_name, role)
VALUES (
    'admin',
    'admin@foldnest.com',
    '$2y$10$YourHashWillBeGeneratedByMigrationScript',
    'Super Admin',
    'super_admin'
) ON DUPLICATE KEY UPDATE username = username;

-- NOTE: The actual hash will be generated by the migration script below.
-- This file is for reference. Use backend/run_migration.php to seed properly.
